extends: standard

env: {
  "browser": true,
  "jquery": true
}

globals: {
  "AV":true,
}

rules: {
  "semi":'off',
  "space-infix-ops":'off',
"space-before-blocks":'off',
"keyword-spacing":'off',
"block-spacing":'off',
"no-trailing-spaces":'off',
"space-before-function-paren":'off',
"padded-blocks":'off',
"comma-spacing":'off',
"indent":'off',
"no-multiple-empty-lines":'off',
"no-unused-vars":'off'
}

